
title: huddersfield-explorer.co.uk
email: your-email@example.com
description: Huddersfield Explored. In West Yorkshire England. An historic town with a fresh future.
baseurl: "/from-scratch/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: "huddersfield-explorer.co.uk"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - octopress-minify-html

# minify_html: false

include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
