
title: huddersfield-explorer.co.uk
email: your-email@example.com
description: Huddersfield Explored. In West Yorkshire England. An historic town with a fresh future.
baseurl: "/from-scratch/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: "huddersfield-explorer.co.uk"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages', '_pages/bars-and-nightclubs', '_pages/eating-out', '_pages/future-investments', '_pages/history-of-huddersfield', '_pages/investig-in-education', '_pages/leisure-and-fitness', '_pages/parks-and-greenspaces', '_pages/shopping-and-business', '_pages/sporting-venues']

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
